# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: "python:3.8" 
#commands to run in the Docker container before starting each job.
before_script:
  - pip install black
  - pip install pytest
  - pip install -e ./koss 
# different stages in the pipeline
stages:
  - Formatter
  - Test
formatter:
  stage: Formatter
  script: 
  - black --check --diff --color --line-length=100 ./
pytest:
  stage: Test
  script:
  - cd koss/tests;pytest -v
