redis:
  host: localhost
  port: 6379
mongodb:
  host: localhost
  port: 27017
scibec:
  host: http://localhost
  port: 3030
service_config:
  file_writer:
    plugin: default
    base_path: ~/Data10

