version: "3.7"

services:
  mongodb-test:
    image: mongo
    ports:
      - "27017:27017"
  redis-test:
    image: redis
    network_mode: host
  scibec-test-server:
    image: scibec-test-server
    build: ./scibec
    network_mode: host
    depends_on:
      - "mongodb-test"
    healthcheck:
      test: curl --fail http://localhost:3030/sessions || exit 1,
      interval: 60s
      timeout: 5s
      start_period: 20s
      retries: 5
  redis-cli:
    image: redis:latest
    depends_on:
      - "redis-test"
    command: redis-cli monitor > /redis.log
    network_mode: host
    volumes:
      - logs:/
volumes:
  logs:
