version: "3.7"

services:
  mongodb-test:
    image: morgana-harbor.psi.ch/bec/mongo
    ports:
      - "27017:27017"
  redis-test:
    image: morgana-harbor.psi.ch/bec/redis
    network_mode: host
  scibec-test-server:
    image: morgana-harbor.psi.ch/bec/scibec
    network_mode: host
    depends_on:
      - "mongodb-test"
    healthcheck:
      test: curl --fail http://localhost:3030/sessions || exit 1,
      interval: 60s
      timeout: 5s
      start_period: 20s
      retries: 5
  # redis-cli:
  #   image: redis:latest
  #   depends_on:
  #     - "redis-test"
  #   command: redis-cli monitor > /data/redis.log
  #   network_mode: host
  #   volumes:
  #     - /tmp:/data
