redis:
  host: "localhost"
  port: 6379
mongodb:
  host: "localhost"
  port: 27017
scibec:
  host: http://localhost
  port: 3030
  beamline: TestBeamline
service_config:
  general:
    reset_queue_on_cancel: True
    enforce_ACLs: False
  file_writer:
    plugin: default
    base_path: ~/Data10
